### ISSUE TITLE
개인정보처리방침 추가

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-api#341]
#337

**Comment by Pyohwan** [comment]
* 자가진단
  * https://www.privacy.go.kr/per/self/selfDiagnosisRegistForm.do?insttCode=&uniqueId=c56453b4d9c8c8b4cdfe0366d630f38e2b2fa6ad58f2bc0d5ff7eaadeb2b&insttNm=&userType=N&infoScale=Y&pipsYN=Y&homepageYN=Y&secureInfoYN=N&cctvYN=N&commisionBizYN=N&infoDept=

**Comment by Pyohwan** [comment]
* 완성
  * https://wiki.jakduk.com/jakdu-k/개인정보처리방침

**Comment by silverprize** [comment]
오 위키를 이리 활용할줄이야
