### ISSUE TITLE
공지 없애기 기능 동작 안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-api#348]
* 관리자 계정으로 들어가서 공지글을 없앨려고 했떠니 403
![2019-02-17 1 06 30](https://user-images.githubusercontent.com/1825642/52902153-4fda7480-3250-11e9-8a73-bbe2cd1b3b55.png)

**Comment by silverprize** [comment]
어드민 계정이 ROLE_ROOT, ROLE_ADMIN 중 어느 것을 갖고 있나요?
ROLE_ADMIN 으로 바꿔주세요

**Comment by Pyohwan** [comment]
@silverprize 
JAKDUK-WEB 에선 ROLE_ADMIN 만 사용하나요?

**Comment by silverprize** [comment]
api 코드가 ROLE_ROOT를 사용하지 않는데요?

**Comment by Pyohwan** [comment]
@silverprize 
JAKDUK-WEB 에 의존성이 없다면 ROLE_ROOT 로 할께요. DB에 ROLE_ROOT 로 쓰고 있어서요.
 ROLE_ADMIN 는 없애도록 하겠습니다.

**Comment by silverprize** [comment]
지우세요
