### ISSUE TITLE
INTERNAL_SERVER_ERROR "all shards failed"

### ISSUE THREAD

**Issue by silverprize** [JakduK/jakduk-api#356]
<img width="471" alt="스크린샷 2019-10-02 오후 7 52 14" src="https://user-images.githubusercontent.com/860087/66038847-36bbd500-e54e-11e9-9cd6-f72a1f9b1538.png">
<img width="790" alt="스크린샷 2019-10-02 오후 7 52 18" src="https://user-images.githubusercontent.com/860087/66038853-391e2f00-e54e-11e9-9f37-294ab8c15b12.png">

**Comment by Pyohwan** [comment]
ES가 많이 아파요

**Comment by Pyohwan** [comment]
복구함
